---
- src: geerlingguy.firewall
  version: 1.3.1
- src: geerlingguy.git
  version: 1.2.0
- src: geerlingguy.nodejs
  version: 3.3.0
- src: geerlingguy.repo-remi
  version: 1.2.0
- src: geerlingguy.security
  version: 1.4.0
